### PR TITLE
Feature/fix presup

### PR DESCRIPTION
**Pull request by HuStmpHrrr**
c.f. #181 

This is the deadliest thing I have ever done...

still WIP.

### CODE REVIEW

**Comment by HuStmpHrrr** [comment]
@Ailrun any way to modularize this mess? I am dead.

**Comment by Ailrun** [comment]
I see some equivalences several times (like `B[Wk][Id,,M] \approx B`) so extracting lemmas for such might help?

**Comment by Ailrun** [comment]
I realized that we don't even need mutual induction for presupposition of `wf_exp`/`wf_sub`. The "enhanced" rules for subtyping provide immediate (inductive) proof for well-formedness of type of `wf_exp`.

**Comment by HuStmpHrrr** [comment]
fix it together in #229

**Pull request merged**
