### PR TITLE
Provide more soundness lemmas

### LINKED ISSUE #144: No use premise
https://github.com/Beluga-lang/McLTT/blob/06389498b20d68b502e3469f8d322abbd0a80ede/theories/Core/Soundness/LogicalRelation/Definitions.v#L306-L309

@Ailrun do you plan on doing anything with this? As it is, it doesn't help anything at all. If you want to remove it or introduce a new substitution, either is fine.

### PR DESCRIPTION
**Pull request by Ailrun**
Closes #144

### CODE REVIEW

**Comment by HuStmpHrrr** [comment]
are you proving a general version of `glu_nat_resp_wk`? I will need this lemma.

**Comment by Ailrun** [comment]
@HuStmpHrrr Please provide the lemma if you want to provide it now, I don't think I would provide much very soon.

**Comment by HuStmpHrrr** [comment]
monotonicity: https://hustmphrrr.github.io/mech-type-theories/MLTT.Soundness.Properties.LogRel.html#24875

**Comment by Ailrun** [comment]
Here I prepare placeholders for now.

**Comment by Ailrun** [comment]
Not really. Let's merge this after your review (if you have any comments)

**Pull request merged**
